In [248]:
import pandas as pd
import numpy as np

In [291]:
results = pd.read_csv("results_toeplitz_small/toeplitz_design_summary.csv")

In [300]:
n = 1000
p_total = 50
p_true = 20
snr = 2
rho = 0.9

In [301]:
current_results = results.loc[(results['n'] == n) & (results['p_total'] == p_total) & (results['p_true'] == p_true) & (results['snr'] == snr) & (results['rho'] == rho) ]

In [302]:
metric = 'f1'
models = ['bandit', 'sequential_g0.3', 'lasso', 'adaptive_lasso', 'forward', 'backward', 'mcmc']

results_mean = current_results[['reward_type'] + [x + '_' + metric + '_mean' for x in models]].set_index('reward_type').loc[['cv_rmse', 'aic', 'bic', 'bayes_factor']]
results_mean.columns = models
results_sd = current_results[['reward_type'] + [x + '_' + metric + '_std' for x in models]].set_index('reward_type').loc[['cv_rmse', 'aic', 'bic', 'bayes_factor']] / np.sqrt(10)
results_sd.columns = models

In [303]:
print(results_mean.style.format(precision=2).to_latex())

\begin{tabular}{lrrrrrrr}
 & bandit & sequential_g0.3 & lasso & adaptive_lasso & forward & backward & mcmc \\
reward_type &  &  &  &  &  &  &  \\
cv_rmse & 0.79 & 0.21 & 0.77 & 0.59 & 0.54 & 0.48 & nan \\
aic & 0.90 & 0.00 & 0.80 & 0.58 & 0.58 & 0.48 & nan \\
bic & 0.75 & 0.02 & 0.76 & 0.46 & 0.51 & 0.46 & nan \\
bayes_factor & 0.64 & 0.00 & 0.66 & 0.51 & 0.47 & 0.46 & 0.47 \\
\end{tabular}

In [304]:
round(results_mean, 2)

,bandit,sequential_g0.3,lasso,adaptive_lasso,forward,backward,mcmc
reward_type,,,,,,,
cv_rmse,0.79,0.21,0.77,0.59,0.54,0.48,NaN
aic,0.90,0.00,0.80,0.58,0.58,0.48,NaN
bic,0.75,0.02,0.76,0.46,0.51,0.46,NaN
bayes_factor,0.64,0.00,0.66,0.51,0.47,0.46,0.47

In [264]:
round(results_sd, 2)

,bandit,sequential_g0.3,lasso,adaptive_lasso,forward,backward,mcmc
reward_type,,,,,,,
cv_rmse,0.02,0.03,0.02,0.02,0.02,0.02,NaN
aic,0.03,0.02,0.02,0.02,0.03,0.03,NaN
bic,0.02,0.02,0.03,0.02,0.02,0.01,NaN
bayes_factor,0.02,0.02,0.05,0.02,0.02,0.01,0.02

In [305]:
metric = 'n_selected'
models = ['bandit', 'sequential_g0.3', 'lasso', 'adaptive_lasso', 'forward', 'backward', 'mcmc']

results_mean = current_results[['reward_type'] + [x + '_' + metric + '_mean' for x in models]].set_index('reward_type').loc[['cv_rmse', 'aic', 'bic', 'bayes_factor']]
results_mean.columns = models
results_sd = current_results[['reward_type'] + [x + '_' + metric + '_std' for x in models]].set_index('reward_type').loc[['cv_rmse', 'aic', 'bic', 'bayes_factor']] / np.sqrt(10)
results_sd.columns = models

In [306]:
print(results_mean.style.format(precision=1).to_latex())

\begin{tabular}{lrrrrrrr}
 & bandit & sequential_g0.3 & lasso & adaptive_lasso & forward & backward & mcmc \\
reward_type &  &  &  &  &  &  &  \\
cv_rmse & 23.1 & 2.4 & 20.9 & 17.6 & 13.9 & 16.8 & nan \\
aic & 23.2 & 0.0 & 16.8 & 14.9 & 10.5 & 14.4 & nan \\
bic & 12.0 & 0.2 & 12.4 & 6.6 & 7.1 & 6.2 & nan \\
bayes_factor & 9.4 & 0.0 & 10.1 & 7.6 & 6.5 & 6.5 & 6.2 \\
\end{tabular}

In [307]:
round(results_mean, 2)

,bandit,sequential_g0.3,lasso,adaptive_lasso,forward,backward,mcmc
reward_type,,,,,,,
cv_rmse,23.1,2.4,20.9,17.6,13.9,16.8,NaN
aic,23.2,0.0,16.8,14.9,10.5,14.4,NaN
bic,12.0,0.2,12.4,6.6,7.1,6.2,NaN
bayes_factor,9.4,0.0,10.1,7.6,6.5,6.5,6.2

In [267]:
round(results_sd, 2)

,bandit,sequential_g0.3,lasso,adaptive_lasso,forward,backward,mcmc
reward_type,,,,,,,
cv_rmse,1.45,0.33,0.73,1.39,0.89,1.27,NaN
aic,1.07,0.20,2.43,1.11,0.72,0.89,NaN
bic,0.27,0.31,0.49,0.40,0.27,0.48,NaN
bayes_factor,0.28,0.27,0.78,0.31,0.26,0.18,0.21

In [298]:
metric = 'test_mse'
models = ['bandit', 'sequential_g0.3', 'lasso', 'adaptive_lasso', 'forward', 'backward', 'mcmc']

results_mean = current_results[['reward_type'] + [x + '_' + metric + '_mean' for x in models]].set_index('reward_type').loc[['cv_rmse', 'aic', 'bic', 'bayes_factor']]
results_mean.columns = models
results_sd = current_results[['reward_type'] + [x + '_' + metric + '_std' for x in models]].set_index('reward_type').loc[['cv_rmse', 'aic', 'bic', 'bayes_factor']] / np.sqrt(10)
results_sd.columns = models

In [299]:
print(results_mean.style.format(precision=2).to_latex())

\begin{tabular}{lrrrrrrr}
 & bandit & sequential_g0.3 & lasso & adaptive_lasso & forward & backward & mcmc \\
reward_type &  &  &  &  &  &  &  \\
cv_rmse & 38.37 & 41.36 & 39.29 & 38.94 & 39.35 & 38.17 & nan \\
aic & 43.04 & 67.19 & 43.30 & 43.50 & 43.71 & 42.76 & nan \\
bic & 42.16 & 62.74 & 42.93 & 43.30 & 42.91 & 43.00 & nan \\
bayes_factor & 40.18 & 51.79 & 40.93 & 41.09 & 41.16 & 41.04 & 41.00 \\
\end{tabular}

In [269]:
round(results_mean, 2)

,bandit,sequential_g0.3,lasso,adaptive_lasso,forward,backward,mcmc
reward_type,,,,,,,
cv_rmse,401.55,568.38,407.32,413.38,423.12,412.77,NaN
aic,408.42,652.39,416.32,417.42,437.60,416.73,NaN
bic,532.95,617.64,450.21,453.08,455.83,453.98,NaN
bayes_factor,515.34,641.22,459.73,450.99,455.45,451.51,454.19

In [143]:
round(results_sd, 2)

,bandit,sequential_g0.3,lasso,adaptive_lasso,forward,backward,mcmc
reward_type,,,,,,,
cv_rmse,0.06,0.22,0.06,0.07,0.07,0.07,NaN
aic,0.07,0.31,0.07,0.07,0.07,0.07,NaN
bic,0.05,0.40,0.05,0.05,0.05,0.05,NaN
bayes_factor,0.09,0.34,0.09,0.09,0.09,0.09,0.09

In [144]:
metric = 'runtime_sec'
models = ['bandit', 'sequential_g0.3', 'lasso', 'adaptive_lasso', 'forward', 'backward', 'mcmc']

results_mean = current_results[['reward_type'] + [x + '_' + metric + '_mean' for x in models]].set_index('reward_type').loc[['cv_rmse', 'aic', 'bic', 'bayes_factor']]
results_mean.columns = models
results_sd = current_results[['reward_type'] + [x + '_' + metric + '_std' for x in models]].set_index('reward_type').loc[['cv_rmse', 'aic', 'bic', 'bayes_factor']] / np.sqrt(10)
results_sd.columns = models

In [145]:
round(results_mean, 2)

,bandit,sequential_g0.3,lasso,adaptive_lasso,forward,backward,mcmc
reward_type,,,,,,,
cv_rmse,45.32,80.25,0.02,0.02,2.26,6.93,NaN
aic,9.40,16.55,0.05,0.04,0.21,1.06,NaN
bic,8.75,16.34,0.05,0.03,0.10,1.09,NaN
bayes_factor,10.04,18.60,0.05,0.04,0.10,1.07,2.51

In [115]:
round(results_sd, 2)

,bandit,sequential_g0.3,lasso,adaptive_lasso,forward,backward,mcmc
reward_type,,,,,,,
cv_rmse,1.52,2.83,0.0,0.0,0.12,0.29,NaN
aic,0.33,0.53,0.0,0.0,0.02,0.04,NaN
bic,0.28,0.52,0.0,0.0,0.00,0.03,NaN
bayes_factor,0.23,0.38,0.0,0.0,0.01,0.03,0.1